"""Small, dated source registry. A vendor claim is not an accuracy certificate."""
from copy import deepcopy

VERIFIED_AT = "2026-09-14"
SOURCES = [
    {"id":"sleeper", "purpose":"Exact league rules, all rosters, rights and public transactions", "url":"https://docs.sleeper.com/", "access":"Built: documented unauthenticated read API", "refresh":"on demand; short league cache, player directory at most daily", "history":"Observed from first local collection; historical league IDs require explicit season", "terms":"Free noncommercial API; retain attribution, keep below documented rate limit", "limitations":["Public reads do not prove pending offers or waiver claims", "Forecast API is not documented", "Ambiguous enum rules remain unresolved"]},
    {"id":"espn", "purpose":"Exact league rules/rosters and native weekly point baseline", "url":"https://github.com/cwendt94/espn-api", "access":"Built: observed private read interface, authorized Firefox or environment auth", "refresh":"league on demand; requested weekly projections 15-minute cache", "history":"Conservative local as-of history only", "terms":"Community wrapper MIT; underlying ESPN data rights are separate. Private experimental adapter; no promise of approved commercial/hosted use", "limitations":["Undocumented interface can change", "Provider update/availability conditioning unknown", "Native totals are not independently rescored or validated", "No pending private transaction certification"]},
    {"id":"fantasypros", "purpose":"Weekly, ROS and seasonal consensus candidate", "url":"https://www.fantasypros.com/api-data/", "access":"MCP initialize verified HTTP 401 OAuth required; REST projections/players HTTP 403 without key. Account not connected.", "refresh":"provider release + pre-decision", "history":"Historical vintages not acquired", "terms":"Official free MCP tool list includes projections; REST production personal use requires HOF, free REST key is prototype-only. See docs/source-access-gap.md; no redistribution entitlement assumed.", "limitations":["Rank accuracy is not point/distribution accuracy", "Inputs may overlap other providers", "Actual authorized response, completeness and issue timestamp still need verification"]},
    {"id":"cbs_projections", "purpose":"Public native weekly and ROS component challenger", "url":"https://www.cbssports.com/fantasy/football/stats/QB/2026/restofseason/projections/ppr/", "access":"Research pages verified HTTP 200; automated ingestion not authorized under reviewed terms", "refresh":"focused source research; no recurring scraper", "history":"Current pages only; unknown revision history", "terms":"Reviewed Paramount terms prohibit unauthorized automated scraping/database storage. No CBS ingestion adapter installed.", "limitations":["No exposed issue time or uncertainty", "Displayed CBS total differs from exact league scoring", "Component tables omit some scoring events"]},
    {"id":"pff", "purpose":"Licensed components, participation and professional forecasts candidate", "url":"https://developer.pff.com/", "access":"Paid candidate; no purchase or authenticated endpoint verified", "refresh":"contract dependent", "history":"Entitlement dependent", "terms":"Predictive-system and persistent derived-data use require rights review", "limitations":["No independent common-target superiority established", "Do not buy until exact fields and use rights confirmed"]},
    {"id":"footballguys", "purpose":"Weekly/ROS forecast challenger", "url":"https://www.footballguys.com/projections/duration/rest-of-season", "access":"Download surface verified; export/import pathway available", "refresh":"provider issue", "history":"Not acquired", "terms":"Subscription/export/programmatic rights unresolved", "limitations":["Verify horizon in payload, not only page label", "No calibrated distribution acquired"]},
    {"id":"etr", "purpose":"Weekly projections and descriptive xFP challenger", "url":"https://establishtherun.com/fantasy-point-projections/", "access":"Paid product reviewed, no feed acquired", "refresh":"provider issue", "history":"Not acquired", "terms":"Obtain suitable export/retention rights", "limitations":["Floor/ceiling definitions and coverage not validated", "ROS rankings are not ROS point means"]},
    {"id":"ffopportunity", "purpose":"Reproducible retrospective opportunity-based xFP", "url":"https://github.com/ffverse/ffopportunity", "access":"Open code/model; not yet an installed live pipeline", "refresh":"after source play-by-play release", "history":"Model described training 2006–2020; version and release must be pinned", "terms":"GPLv3 code; CC BY-SA 4.0 model/data per repository", "limitations":["Describes opportunities already received; not a future-usage forecast", "Residual is not automatically luck or profitable buy-low", "Applicable scoring features require audit"]},
    {"id":"official_nfl", "purpose":"Reported health/practice, transactions and completed game observations", "url":"https://www.nfl.com/injuries/", "access":"Public official pages; focused session research and dated dossier storage", "refresh":"practice reports, transactions, inactives and material news", "history":"Only archived observations are as-of usable", "terms":"Publisher terms; keep summaries and links, no article redistribution", "limitations":["Status does not equal probability of playing or restored workload", "Team announcements may not provide return forecasts"]},
    {"id":"injury_challengers", "purpose":"Draft Sharks / SIC / SportsMedAnalytics case-specific challengers", "url":"https://www.draftsharks.com/ros-rankings", "access":"Paid/free surfaces reviewed; no validated feed selected", "refresh":"target dependent", "history":"Common modern forecast ledger not obtained", "terms":"Provider specific", "limitations":["No independently demonstrated universal best predictor found", "Separate incidence, duration, active probability and post-return workload", "Do not apply a risk adjustment already included in a projection"]},
    {"id":"the_odds_api", "purpose":"Book-by-book event props and alternate thresholds", "url":"https://the-odds-api.com/liveapi/guides/v4/", "access":"Key required; not purchased or connected", "refresh":"before relevant decision, timestamp each book", "history":"Vendor advertises prop snapshots since 2023-05-03; not acquired", "terms":"Permitted retention and raw redistribution must match current plan terms", "limitations":["Line is not a mean", "Dependent books are not independent samples", "Player absence settlement often differs from fantasy scoring"]},
    {"id":"kalshi", "purpose":"Public short-horizon contract/threshold evidence", "url":"https://docs.kalshi.com/", "access":"Public read endpoints verified; no trading", "refresh":"short-lived event snapshots, explicit expiry", "history":"Locally observed only; no retrospective price reconstruction", "terms":"Preserve market rules, settlement source and linked member/API terms", "limitations":["Contract prices include spreads/liquidity effects", "Two threshold quotes do not identify a mean or player joint distribution", "Team futures do not allocate production to a particular player"]},
    {"id":"moneyball_archive", "purpose":"Reuse prior player dossiers with their original evidence cutoffs", "url":"local:moneyball/.moneyball/draft/room/deck.json", "access":"Explicit local import; private runtime only", "refresh":"Structural evidence retained, volatile claims revisited only when relevant", "history":"Sep 2026 dossiers, never backdated into the new store", "terms":"Private composite research; underlying source rights preserved", "limitations":["Old dossiers are not fresh status reports", "Prior synthetic title deltas/heuristic values are not calibrated"]},
]


def registry(source_id=None):
    rows = [s for s in SOURCES if source_id is None or s["id"] == source_id]
    return {"review_date":VERIFIED_AT, "status":"Access and suitability review, not predictive-accuracy ranking", "sources":deepcopy(rows)}
